export const sensitiveLogRedaction = {
  paths: [
    'req.headers.authorization',
    'req.headers.cookie',
    'req.headers["x-api-key"]',
    'req.headers["x-supabase-auth"]',
    'req.headers["x-revenuecat-signature"]',
    'req.headers["x-webhook-signature"]',
    'res.headers["set-cookie"]',
    'authorization',
    'cookie',
    'accessToken',
    'refreshToken',
    'password',
    'passwordHash',
    'token',
    '*.accessToken',
    '*.refreshToken',
    '*.password',
    '*.passwordHash',
    '*.token',
  ],
  censor: '[redacted]',
};
