export const VALIDATION_LIMITS = {
  emailMaxLength: 254,
  displayNameMinLength: 1,
  displayNameMaxLength: 80,
  workspaceNameMinLength: 1,
  workspaceNameMaxLength: 80,
  participantNameMinLength: 1,
  participantNameMaxLength: 60,
  participantInitialsMinLength: 1,
  participantInitialsMaxLength: 4,
  taskTitleMinLength: 1,
  taskTitleMaxLength: 140,
  taskDescriptionMaxLength: 1000,
  agreementTitleMinLength: 1,
  agreementTitleMaxLength: 140,
  agreementDescriptionMaxLength: 1000,
  meetingTitleMinLength: 1,
  meetingTitleMaxLength: 120,
  meetingNoteTextMaxLength: 2000,
  meetingSectionsPerMeetingMax: 20,
  notesPerMeetingSectionMax: 50,
  tasksPerMeetingSectionMax: 50,
  agreementsPerMeetingSectionMax: 50,
  participantsPerWorkspaceMax: 20,
  meetingsPerSyncRequestMax: 100,
  tasksPerSyncRequestMax: 300,
  agreementsPerSyncRequestMax: 300,
  normalRequestBodyBytesMax: 1024 * 1024,
  apiIdMaxLength: 128,
  passwordMinLength: 8,
  passwordMaxLength: 256,
  authTokenMaxLength: 4096,
  calendarTitleMaxLength: 140,
  calendarRedirectUrlMaxLength: 2048,
  aiLocaleMaxLength: 16,
  summaryTextMaxLength: 1000,
  summaryListItemsMax: 20,
  purchaseTokenMaxLength: 4096,
  productIdMaxLength: 256,
  providerStatusMaxLength: 80,
} as const;

export type ValidationLimits = typeof VALIDATION_LIMITS;
